from .rt_index import index
from .rt_about import about
from .rt_login import login
from .rt_register import register
from .rt_about import about
from .rt_user import user
from .rt_createpaste import create
from .rt_viewpaste import view
from .rt_deletepaste import delete